# log dir 
log_dir: /data/AmitRoyChowdhury/vedant/DeepfakeBench/logs

# model setting
pretrained: null
model_name: foundation_detector
backbone_name: siglip

#backbone setting
backbone_config:
  mode: original
  num_classes: 1
  inc: 3
  dropout: false

# dataset
all_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV]
train_dataset: [Celeb-DF-v1]
test_dataset: [Celeb-DF-v1]

compression: c23
train_batchSize: 8  
test_batchSize: 8   
workers: 8   
frame_num: {'train': 16, 'test': 16}   
resolution: 224   
with_mask: false   
with_landmark: false   
video_mode: True  
clip_size: 8  # using 8 frames for the temporal safety classifier

# data augmentation
use_data_augmentation: true  
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.5
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100

mean: [0.5, 0.5, 0.5]
std: [0.5, 0.5, 0.5]

optimizer:
  type: adam
  adam:
    lr: 0.0001
    beta1: 0.9
    beta2: 0.999
    eps: 0.00000001
    weight_decay: 0.0005
    amsgrad: false

lr_scheduler: null   
nEpochs: 15   
start_epoch: 0   
save_epoch: 1   
rec_iter: 100   
logdir: ./logs   
manualSeed: 1024   
save_ckpt: true   
save_feat: true   

loss_func: cross_entropy
losstype: null

metric_scoring: auc   
cuda: true   
cudnn: true   
